# Generated by Django 2.2.11 on 2020-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tthgh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tthgh',
            name='rfrgsfgs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
